on:
  - push
name: Build artifacts
jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo 'test artifact 3' >> artifact.txt
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifact.txt
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: ./
      - name: Check
        run: |
          pwd
          ls -la
      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: latest
          files: |
            artifact.txt
